"""empty message

Revision ID: 230300c916aa
Revises: 
Create Date: 2021-10-13 21:49:54.479417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230300c916aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('sobre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity')
    # ### end Alembic commands ###
