"""empty message

Revision ID: 7adf562d50ae
Revises: 
Create Date: 2021-10-10 09:08:36.365200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adf562d50ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nome'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('nome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity')
    # ### end Alembic commands ###
